services:
  app:
    build:
      context: ./bin/webserver
      dockerfile: Dockerfile
    container_name: lanchonete_app
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - ../:/app
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload